//
// Copyright (c) 2017 The nanoFramework project contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#include <Core.h>

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_mscorlib;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_Native;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Hardware_Stm32;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_Events;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_Events_EventSink_DriverProcs;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Gpio;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_I2c;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Pwm;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_SerialCommunication;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Spi;

const CLR_RT_NativeAssemblyData *g_CLR_InteropAssembliesNativeData[] =
{
	&g_CLR_AssemblyNative_mscorlib,
	&g_CLR_AssemblyNative_nanoFramework_Runtime_Native,
	&g_CLR_AssemblyNative_nanoFramework_Hardware_Stm32,
	&g_CLR_AssemblyNative_nanoFramework_Runtime_Events,
	&g_CLR_AssemblyNative_nanoFramework_Runtime_Events_EventSink_DriverProcs,
	&g_CLR_AssemblyNative_Windows_Devices_Gpio,
	&g_CLR_AssemblyNative_Windows_Devices_I2c,
	&g_CLR_AssemblyNative_Windows_Devices_Pwm,
	&g_CLR_AssemblyNative_Windows_Devices_SerialCommunication,
	&g_CLR_AssemblyNative_Windows_Devices_Spi,
	NULL
};

uint16_t g_CLR_InteropAssembliesCount = (8 + 2);
