//
// Copyright (c) 2017 The nanoFramework project contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#include <chversion.h>

#ifndef _TARGET_OS_H_
#define _TARGET_OS_H_

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define VERSION_MAJOR 0U
#define VERSION_MINOR 9U
#define VERSION_BUILD 99U
#define VERSION_REVISION 999U

#define TARGETINFOSTRING "Debug build with ChibiOS v" CH_VERSION "." STR(CH_VERSION_MONTH)

#define NANOCLR_LIGHT_MATH FALSE
#define DP_FLOATINGPOINT FALSE

#define SUPPORT_ANY_BASE_CONVERSION TRUE

#define HAS_CONFIG_BLOCK TRUE

#define NANOCLR_REFLECTION TRUE

#define NANOCLR_SYSTEM_COLLECTIONS TRUE

#endif /* _TARGET_OS_H_ */
