//
// Copyright (c) 2017 The nanoFramework project contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#ifndef _TARGET_CHIBIOS_NANOCLR_H_
#define _TARGET_CHIBIOS_NANOCLR_H_

// enable SPIFFS
#define NF_FEATURE_USE_SPIFFS FALSE

// set preference to enable (or not) the RTC subsystem
#define HAL_USE_RTC TRUE

// takes care of enabling the HAL subsystems required for API options

// enable SPI
#define HAL_USE_SPI TRUE

// enable I2C
#define HAL_USE_I2C TRUE

// enable PWM
#define HAL_USE_PWM TRUE

// enable ADC
#define HAL_USE_ADC TRUE

// enable DAC
#define HAL_USE_DAC TRUE

// enable UART subsystem
#define HAL_USE_UART TRUE

// set when networking is enabled
#define HAL_USE_MAC TRUE

// set when filesystem is enabled
#define HAL_USE_SDC TRUE

// set when watchod is enabled
#define HAL_USE_WDG TRUE

// enable CAN
#define HAL_USE_CAN TRUE

// enable CRC32 module
#define HAL_NF_USE_STM32_CRC        TRUE

// enable STM32 ONEWIRE (from nf overlay)
#define HAL_NF_USE_STM32_ONEWIRE TRUE

// enable USB MSD (from ChibiOS Contrib)
#define HAL_USBH_USE_MSD     FALSE

#undef STM32_I2C_USE_DMA
#define STM32_I2C_USE_DMA TRUE


//#undef STM32_I2C_USE_I2C4
//#define STM32_I2C_USE_I2C4 TRUE   // Override mcuconf.h ( set to FALSE)

//#define STM32_I2C_I2C4_RX_DMA_STREAM        STM32_DMA_STREAM_ID(1, 2)
//#define STM32_I2C_I2C4_TX_DMA_STREAM        STM32_DMA_STREAM_ID(1, 5)

//#undef STM32_I2C4_RX_DMA_MSK 
//#undef STM32_I2C4_TX_DMA_MSK
//#define STM32_I2C4_RX_DMA_MSK               (STM32_DMA_STREAM_ID_MSK(1,2)  |  \
//                                             STM32_DMA_STREAM_ID_MSK(2,1)  | \
//                                             STM32_DMA_STREAM_ID_MSK(1,1)) 
//#define STM32_I2C4_TX_DMA_MSK                STM32_DMA_STREAM_ID_MSK(2,2)
//
//#undef STM32_I2C_I2C4_RX_DMA_STREAM
//#undef STM32_I2C_I2C4_TX_DMA_STREAM
//#define STM32_I2C_I2C4_RX_DMA_STREAM        STM32_DMA_STREAM_ID(1,1)
//#define STM32_I2C_I2C4_TX_DMA_STREAM        STM32_DMA_STREAM_ID(1,6)
//
//#undef STM32_I2C_I2C4_RX_DMA_STREAM
//#define STM32_I2C_I2C4_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
//#undef STM32_I2C_I2C4_TX_DMA_STREAM
//#define STM32_I2C_I2C4_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)

#endif
